### PR TITLE
Add arm64 back

### PR DESCRIPTION
**Pull request by AaronDewes**
This adds ARM64 again. Many people wanted this in Desktop, and this would help to add it. I also made it a bit faster.

## Changes to speed up ARM64

- Use two parallel make jobs
- Compile directly on ARM64 instead of cross-compiling
- Don't use Docker anymore
- Use ccache

### CODE REVIEW

**Comment by niik** [comment]
> Many people wanted this in Desktop

Hey @AaronDewes :wave: Could you provide some links to this? I was aware of the initiative to support ARM64 on Windows (https://github.com/desktop/desktop/issues/9034) but the arm64 work we removed in https://github.com/desktop/dugite-native/pull/315 was specifically for Linux which isn't a supported platform for GitHub Desktop at the moment

**Comment by AaronDewes** [comment]
https://github.com/shiftkey/desktop/issues/251

**Comment by AaronDewes** [comment]
It should now build directly on arm64, so it doesn't cross-compile anymore, which should speed up the build.

**Comment by AaronDewes** [comment]
The macOS builds are failing, but I don't think it's caused by this PR.

**Comment by AaronDewes** [comment]
I don't know why Ubuntu and macOS builds are failing, macOS just seems to clone from an invalid repo: https://travis-ci.org/github/desktop/dugite-native/jobs/703526404#L860.

**Comment by AaronDewes** [comment]
ARM64 still takes a bit longer, but not 10 minutes anymore. Ubuntu builds are fixed now.

**Comment by AaronDewes** [comment]
I've rebased it now. The arm64 build takes about 5 minutes now, macOS is still failing for some reasons.

**Comment by AaronDewes** [comment]
Seems impossible again now, GitHub actions has no arm64 support and it would be really slow again

**Comment by theofficialgman** [comment]
github actions has self hosted arm/arm64 support... is that not an option?

**Comment by theofficialgman** [comment]
https://aws.amazon.com/blogs/compute/building-arm64-applications-on-aws-graviton2-using-the-aws-cdk-and-self-hosted-runners-for-github-actions/
info here on how to do that ^

**Pull request closed without merging**
