### PR TITLE
Get LFS only when GIT_LFS_VERSION is set and warn if not

### PR DESCRIPTION
**Pull request by hbons**
I tried to move the warnings at the end of each `build-*.sh` to a separate shared script, but couldn't make it work due to the relative paths used. I also tried to move that logic to the end of `build.sh` but that part doesn't get executed for some reason. Help welcome there.

### CODE REVIEW

**Comment by hbons** [comment]
Just noticed that the cert download check is always negative. I think it's the relative path again...

**Comment by hbons** [comment]
Thanks for your feedback. I've made the requested changes.

From your comment in #120 I thought you wanted the warnings as a summary at the end. Right now the "check static linking" outputs a huge amount of messages (at least on my Linux system, maybe that can be suppressed) which makes the warnings where they are now less useful.

I think the CA cert check should return `exit 1` to be on the safe side, as it's not a user option and they're essential. This is something that can easily go wrong depending on your network connection, is easy to miss and you don't want developers to bundle a broken Git build by accident. Let me know what you think.

**Comment by hbons** [comment]
Example of the static linking research output: https://gist.github.com/hbons/de1e622efb08dc5e1c33a3a3243c2435

**Comment by shiftkey** [comment]
> Right now the "check static linking" outputs a huge amount of messages (at least on my Linux system, maybe that can be suppressed) which makes the warnings where they are now less useful.

Let's talk about that in another PR if you'd like to control that output.

> I think the CA cert check should return `exit 1` on fail to be on the safe side, as it's not a user option and they're essential.

👍

**Comment by hbons** [comment]
Feel free to merge this if you're happen with the commits. I'll create new PRs for the exit on CA download error and the static linking output.

**Comment by shiftkey** [comment]
Thanks again @hbons!

**Pull request merged**
