### PR TITLE
Add Windows 32-bit support

### LINKED ISSUE #86: 32-bit Windows support
There's some requests for Desktop to support 32-bit Windows https://github.com/desktop/desktop/issues/1214 and without a 32-bit Git this isn't technically possible.

Someone who wants to see this supported needs to:

 - add an entry to [`.travis.yml`](https://github.com/desktop/dugite-native/blob/master/.travis.yml) so that TravisCI will build the Windows platform using the 32-bit Git for Windows release and 32-bit Git LFS release. You can see the Git for Windows releases [here](https://github.com/git-for-windows/git/releases) and the Git LFS releases [here](https://github.com/git-lfs/git-lfs/releases). Ensure you also use the right checksums, as the build will fail if it doesn't get the bits it expects.

You can use the 64-bit Windows config as a starting point:

https://github.com/desktop/dugite-native/blob/7403fd7cb0a5aff62c4eeda1566bb897dcc4a63b/.travis.yml#L22-L29

 - [this script](https://github.com/desktop/dugite-native/blob/master/script/build-win32.sh) doesn't differentiate between 32-bit or 64-bit Windows, and it has some hard-coded `mingw64` paths that don't exist in the 32-bit version of Git for Windows - I recommend using an environment variable like `ARCH=32` or `ARCH=64` to differentiate the desired architecutre.

 - update the 64-bit Windows configuration so that it uses a `ARCH=64` environment variable

### PR DESCRIPTION
**Pull request by MagicMarvMan**
Fixes #86 

- [x] Add environment variables which differentiate between 64bit and 32bit windows
- [x] Add updated packages with 32bit compatibility
- [x] Add support for mingw32
- [x] emitted package contains architecture for Windows
- [x] Done!

### CODE REVIEW

**Comment by shiftkey** [comment]
Looking good so far. I knew there was something I overlooked with my previous list - the package step doesn't have any architecture-specific checks, so both Windows builds will emit the same name currently:

https://github.com/desktop/dugite-native/blob/9c7cfcf2a213c598485fcd3043030a4787824938/script/package.sh#L34-L36

This means publishing releases will likely fail currently because it will block on overwriting an existing file. Maybe appending `64bit` or `32bit` to the filename here would be ideal, based on `WIN_ARCH`?

**Comment by MagicMarvMan** [comment]
Let's give it a try, wait a minute, please....

**Comment by MagicMarvMan** [comment]
Hmmm.... When i run the build, there is a very strange output. Could you maybe take a quick look at the whole Travis log and maybe tell me what's wrong?

**Comment by horus68** [comment]
One more trying to use latest github in a Windows 10 32 bits.
I was trapped in the update process, getting an alert to updated but no warning that it only worked for win64. The update didn't worked (msi or EXE) and then the old desktop app refused to send a PR to origin because my login was refused (but it was able to download or synch!). 
I was able to logout and login but no upload!
Bad, bad, really bad service.

## The solution
I'm not a developer, just a translator and I need a visual interface to work (Gui)
For those trying to build a version for win32: Thanks for your work but, for me, there is no need to create such version.
I moved way into another Gui client and in one hour I was able to learn it and to get my repo from github, work locally, creating a pull to origin and merge it.

So i now use this software Gitkraken `https://www.gitkraken.com/download/windows`
I found it better than the old Github desktop, easy and simple to use, even for me that hate Git clients!

For others: I didn't test it but i think this could also work for you: `https://gitforwindows.org/`

Note: URL are in code as i'm not here promoting the software!

**Pull request merged**
