### PR TITLE
Bundle smimesign for Windows/macOS

### PR DESCRIPTION
**Pull request by mastahyeti**
This PR bundles [smimesign](https://github.com/github/smimesign) in the same way we're already bundling git-lfs. Instead of putting binaries under `/libexec/git-core`, this puts them under `/bin`.

My one concern is for older versions of macOS. The APIs used by smimesign were introduced in macOS 10.12, so it does not work with older versions. My understanding is that this project supports macOS back to 10.9. Is it okay to ship a binary that doesn't work on some supported systems?

### CODE REVIEW

**Comment by shiftkey** [comment]
@mastahyeti 

> My understanding is that this project supports macOS back to 10.9. Is it okay to ship a binary that doesn't work on some supported systems?

We compile Git against 10.9 for compatibility reasons, and I believe this was chosen because Electron apps are supported on macOS going back to 10.9 (and they still support that).

I'm trying to think of the worst case scenario here. Would it be something like this?

 - user installs app on old version of macOS (say 10.9)
 - app bundles dugite with smimesign
 - app sets Git config values incorrectly to enable smimesign
 - user gets error in app (what sort of error would happen here if we use smimesign on an unsupported macOS?) when trying to perform some Git operation that indirectly invokes `smimesign`

In that case I think the onus is on us to document things better in here, and for the application authors to be aware of the constraints when enabling `smimesign` in the app. Thoughts?

**Comment by mastahyeti** [comment]
> user gets error in app (what sort of error would happen here if we use smimesign on an unsupported macOS?) when trying to perform some Git operation that indirectly invokes smimesign

The user would see a linker error, since the APIs needed by smimesign aren't available in older macOS SDKs:

```
dyld: Symbol not found: _kSecKeyAlgorithmECDSASignatureDigestX962SHA1
  Referenced from: /Users/travis/build/mastahyeti/foobar/./smimesign (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/travis/build/mastahyeti/foobar/./smimesign
```

> In that case I think the onus is on us to document things better in here, and for the application authors to be aware of the constraints when enabling smimesign in the app. Thoughts?

I wonder if we could even wrap the binary in a script that checks the macOS version and gives a more useful error message?

**Comment by shiftkey** [comment]
> I wonder if we could even wrap the binary in a script that checks the macOS version and gives a more useful error message?

There's nothing that can be done within the `smimesign` binary itself to platform check and bail out?

**Comment by mastahyeti** [comment]
This definitely isn't my area of expertise, but I'm not aware of a way for a binary to do anything before the linker runs.

**Comment by mastahyeti** [comment]
Bump 😬

**Comment by shiftkey** [comment]
@mastahyeti apologies for the delay in this, but I think I'm fine to get this in after we've got a scriptable way to pull in the latest version of `smimesign`.

The things that I need are:
 - a canonical source for the latest release - https://github.com/github/smimesign/releases looks promising
 - a list of the checksums associated with the installers, that I can parse and dump into the `dependencies.json` file at the root of the repository

I'm happy to help with the scripting itself, but ultimately I need that source of truth to start from and then flow the updates into the project - rather than having people manually editing files as it currently is.

**Comment by shiftkey** [comment]
Coming back to the problem of running `smimesign` on older platforms while integrated into `dugite`, I have two questions to help figure out our options beyond it crashing hard:

 - `smimesign` needs to be enabled via config, right? And `smimesign` needs to be on the PATH 

> `git config --local gpg.x509.program smimesign`

 - if we're running on an unsupported version of macOS, `smimesign` (or it's wrapper) cannot just no-op - it needs to error gracefully to indicate that it can't be used in this setup?

**Comment by mastahyeti** [comment]
> a canonical source for the latest release - https://github.com/github/smimesign/releases looks promising

Yep. The releases page is the best we've got.

> a list of the checksums associated with the installers, that I can parse and dump into the dependencies.json file at the root of the repository.

This is trickier. The installers are generated by TravisCI and AppVeyor when a new tag is pushed. I can look at how other projects are doing this, but I'm afraid the automation might hurt us here.

> smimesign needs to be enabled via config, right? And smimesign needs to be on the PATH

Yeah. It doesn't _do_ anything unless you configure Git to use it.

> if we're running on an unsupported version of macOS, smimesign (or it's wrapper) cannot just no-op - it needs to error gracefully to indicate that it can't be used in this setup?

I guess. It seems unfriendly for it to just spit out a nonsensical linker error.

**Comment by shiftkey** [comment]
> The installers are generated by TravisCI and AppVeyor when a new tag is pushed. I can look at how other projects are doing this, but I'm afraid the automation might hurt us here.

I cobbled together a two-stage process that might help:

1) generate checksum files for each package and adds them to the draft GitHub release
2)  scripted release process that takes the draft artefacts, reads the checksum files and appends them to the release notes body before publishing

Here's one I prepared earlier: https://github.com/desktop/dugite-native/releases/tag/v2.19.1-4

Ideally I'd come back in and strip the `.sha256` files (or replace them with a signed checksum file like Git LFS does) once I'm happy with it, but that's low-priority for me.

> It seems unfriendly for it to just spit out a nonsensical linker error.

For the moment I'm fine with pulling this in without any config changes. I'm happy to give feedback on this when I start trying to use it in Desktop itself.

**Comment by mastahyeti** [comment]
> scripted release process that takes the draft artefacts, reads the checksum files and appends them to the release notes body before publishing

Where is this part happening?

**Comment by shiftkey** [comment]
@mastahyeti [`script/update-git-lfs.js`](https://github.com/desktop/dugite-native/blob/cccb9158051150bcf6e990004ea308b0b38d16ef/script/update-git-lfs.js) and [`script/update-git.js`](https://github.com/desktop/dugite-native/blob/cccb9158051150bcf6e990004ea308b0b38d16ef/script/update-git.js) are the current examples I have working and being used.

**Pull request closed without merging**
