### PR TITLE
updated git-lfs version

### PR DESCRIPTION
**Pull request by sudhanshumonga**

### CODE REVIEW

**Comment by outofambit** [comment]
Hi @sudhanshumonga thanks for opening this pull request. We're not looking to upgrade `git-lfs` right now, so I'm going to close this pull request. Is there a particular feature in a more recent version of `git-lfs` that you're needing? Happy to talk more if so!

**Comment by sudhanshumonga** [comment]
@outofambit I want to upgrade git-lfs because the software build of our MacOS is failing notarization. Earlier this was a warning, lately it has been tagged as an error by Apple. We are bundling dugite in our app, so we are unable to ship the app.

**Comment by outofambit** [comment]
@sudhanshumonga we're using the version of `git-lfs` currently in `dugite-native` for github.com/desktop/desktop, which is signed and notarized for macOS 10.15. can you share what erro output is leading you to believe the notarization error you're seeing is due to `dugite-native`?

**Comment by outofambit** [comment]
@sudhanshumonga nevermind, i've confirmed and documented the problem in #318. working on a fix now

**Comment by sudhanshumonga** [comment]
hey @outofambit  so can I expect the fix in the next release? 
Thanks!

**Comment by outofambit** [comment]
@sudhanshumonga yes absolutely! if you need something in the meantime, https://github.com/desktop/dugite-native/releases/tag/v2.23.1-rc1 should unblock you. its a little rough, but should work!

also, thanks for bringing this issue to our attention so quickly! definitely helped my debugging process on some related issues i saw independently.

**Comment by sudhanshumonga** [comment]
@outofambit thank you so much for a prompt fix, our app was notarized successfully! 👍 :)

**Pull request closed without merging**
